name: Build and Store

on:
  push:
    branches:
      - main  # The branch to monitor (default branch is 'main')

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        npm install
        npm run build

    - name: Save build artifact
      uses: actions/upload-artifact@v4  # Updated version to v4
      with:
        name: build-artifact
        path: ./build




# name: Build and Deploy

# on:
#   push:
#     branches:
#       - main  # Monitor the 'main' branch for changes

# jobs:
#   build:
#     runs-on: ubuntu-latest  # Use the latest Ubuntu runner

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3  # Checkout your repository

#     - name: Install dependencies
#       run: |
#         npm install  

#     - name: Start app
#       run: |
#         node app.js &

#     # Optionally, save the artifact if needed
#     - name: Save build artifact
#       uses: actions/upload-artifact@v3
#       with:
#         name: build-artifact
#         path: ./  # You can adjust this if you want to store specific files as artifacts

    # # Notify your server for deployment (if applicable)
    # - name: Notify server for deployment
    #   run: |
    #     curl -X POST https://your-server.com/deploy  # Notify your server (adjust URL)
